on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
jobs:
  validate_commit:
    name: Validating Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          echo "MSG=$(git log --format=%B -n 1 ${{github.event.after}})" >> $GITHUB_ENV
      - name: Install Commitizen
        run: pip install -U Commitizen
      - name: Check For Valid Commit Message
        run: cz check -m "${{env.MSG }}"
  terraform_pr_checks:
    needs: validate_commit
    name: Checking For Folder Changes
    runs-on: ubuntu-latest
    outputs:
      dns_changes: ${{ steps.changed-files-dns.outputs.any_changed}}
      lke_changes: ${{ steps.changed-files-dns.outputs.any_changed}}
    steps:
    - uses: hashicorp/setup-terraform@v2
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - name: Check For Changes in lke folder
      id: changed-files-lke
      uses: tj-actions/changed-files@v34
      with:
        files: |
          lke/**

    - name: Check For Changes in dns folder
      id: changed-files-dns
      uses: tj-actions/changed-files@v34
      with:
        files: |
          dns/**

    - name: Run step if any file(s) in the lke folder change
      if: steps.changed-files-lke.outputs.any_changed == 'true'
      run: |
        echo "One or more files in the lke folder has changed."
        echo "List all the files that have changed: ${{ steps.changed-files-lke.outputs.all_changed_files }}"

    - name: Run step if any file(s) in the dns folder change
      if: steps.changed-files-dns.outputs.any_changed == 'true'
      run: |
        echo "One or more files in the dns folder has changed."
        echo "List all the files that have changed: ${{ steps.changed-files-dns.outputs.all_changed_files }}"

  terraform_dns_checks:
    needs: terraform_pr_checks
    if: ${{needs.terraform_pr_checks.outputs.dns_changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - run: terraform init
      working-directory: ./dns

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./dns

    - name: Terraform Plan
      id: plan
      working-directory: ./dns
      run: terraform plan -var="token=${{ secrets.TF_VAR_TOKEN }}" -var="nodebalancer_ip=${{ secrets.TF_VAR_nodebalancer_ip}}" -var="soa_email=${{ secrets.TF_VAR_soa_email}}" -var-file="terraform.tfvars" -no-color
      continue-on-error: true

    - uses: actions/github-script@v6
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
          })

          // 2. Prepare format of the comment
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
